service: jest-with-lambda
frameworkVersion: '3'

plugins:
  - serverless-offline
  - serverless-bundle

provider:
  name: aws
  runtime: nodejs20.x

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get
